[dependabot][prod][npm] - (deps): Bump the prod-others group with 1 update (#283)
* [dependabot][prod][npm] - (deps): Bump the prod-others group with 1 update

Bumps the prod-others group with 1 update: [@actions/core](https://github.com/actions/toolkit/tree/HEAD/packages/core).


Updates `@actions/core` from 1.10.0 to 1.10.1
- [Changelog](https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md)
- [Commits](https://github.com/actions/toolkit/commits/HEAD/packages/core)

---
updated-dependencies:
- dependency-name: "@actions/core"
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: prod-others
...

Signed-off-by: dependabot[bot] <support@github.com>

* Add explanation for outdated JS files

* Re-compile TS files

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Yoanm <4410697+yoanm@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,18 +18,29 @@ jobs:
     steps:
       - name: "Checkout"
         uses: actions/checkout@v4
+
       - name: Retrieve node version for the action
         id: node_version
         run: |
           make get-action-nodejs-version
           echo "version=$(make get-action-nodejs-version)" >> $GITHUB_OUTPUT
+
       - name: Configure NodeJs version
         uses: actions/setup-node@v4
         with:
           node-version: '${{ steps.node_version.outputs.version }}'
+
       - name: "Build "
         run: make build && make package
+
       - name: "Detect forgotten compilation before push"
-        run: test -z "$(git diff --name-only dist/)"
+        run: |
+          if test -z "$(git diff --name-only dist/)"; then
+            echo "JS files up-to-date 👌";
+            exit 0;
+          fi
+          echo "::error::JS files are outdated ! Run 'nvm use && make build && make package && git add dist && git commit -m \"Re-compile TS files\"'.";
+          exit 1;
+
       - name: "Lint"
         run: make lint
